apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-blue
  labels:
    app: flask-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      version: blue
  template:
    metadata:
      labels:
        app: flask-app
        version: blue
    spec:
      containers:
      - name: flask-container
        image: chavindushirantha/python-app
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production